[theme]
primaryColor = "#1E90FF"  # Bleu vif
backgroundColor = "#F0F8FF"  # Alice blue
secondaryBackgroundColor = "#E6F3FF"  # Bleu très clair
textColor = "#000000"  # Noir
font = "sans serif"

[server]
maxUploadSize = 50  # Taille max des fichiers uploadés en MB